
create table raw.enfrentamientos_violentas_policia (
    id character varying,
    fecha character varying,
    year character varying,
    municipio character varying,
    clave_municipio character varying,
    estado character varying,
    clave_estado character varying,
    tipo_de_documento character varying,
    clave_tipo_de_documento character varying,
    tipo_de_evento character varying,
    clave_tipo_de_evento character varying,
    heridos_autoridades character varying,
    muertos_autoridades character varying,
    detenidos character varying,
    heridos_delincuencia character varying,
    muertos_delincuencia character varying,
    heridos_civiles character varying,
    muertos_civiles character varying,
    policia_federal character varying,
    sedena character varying,
    semar character varying,
    pgr character varying,
    policia_estatal character varying,
    policia_municipal character varying,
    afi character varying,
    estado_mayor character varying
);