create table views.cenapi_by_year as

select
    cve_geoid,
    extract(year from fecha_reporte) as year,
    count(*)
from
    processed.cenapi
group by
    cve_geoid,
    year
order by
    cve_geoid,
    year
;


        -- fecha_reporte,
        -- hora_reporte,
        -- fecha_evento,
        -- hora_evento,
        -- estado,
        -- clave_estado,
        -- municipio,
        -- clave_municipio,
        -- nacionalidad,
        -- estatus_migratorio,
        -- sexo,
        -- fecha_de_nacimiento,
        -- edad,
        -- senas_particulares,
        -- descripcion_senas_particulares,
        -- descripcion_media_filiacion,
        -- padecimiento_o_enfermedad,
        -- discapacidad_mental,
        -- tipo_de_discapacidad_mental,
        -- descripcion_de_vestimenta,
        -- contaba_con_aparatos_de_comunicacion,
        -- ocupacion,
        -- relacion_con_grupos_delictivos,
        -- fecha_de_ultimo_avistamiento,
        -- hora_de_ultimo_avistamiento,
        -- tipo_de_vehiculo,
        -- marca_de_vehiculo,
        -- ano_del_vehiculo,
        -- discapacidad_fisica,
        -- procedencia,
        -- pais_de_origen,
        -- entidad,
        -- etnia,
        -- anteojos,
        -- fecha_de_localizacion,
        -- hora_de_localizacion,
        -- vivo_o_muerto,
        -- posible_causa_desaparicion,
             -- condicion_encontrado,
        -- estado_localizado,
        -- clave_estado_localizado,
        -- municipio_localizado,
        -- clave_municipio_localizado,
        -- ente_que_localiza,
        -- fecha_de_ingreso,
        -- hora_de_ingreso,
        -- fecha_probable_de_fallecimiento,
        -- causas_de_fallecimiento,
        -- peso,
        -- estatura,
        -- forma_de_la_cara,
        -- color_de_ojos,
        -- tipo_de_ojos,
        -- tez,
        -- forma_del_cabello,
        -- largo_del_cabello,
        -- color_del_cabello,
        -- tamano_de_orejas,
        -- forma_del_menton,
        -- tamano_de_la_nariz,
        -- tipo_de_nariz,
        -- grosor_de_labios,
        -- tipo_de_frente,
        -- cejas,
        -- tipo_de_cejas,
        -- tamano_de_la_boca,
        -- barba,
        -- bigote,
        -- submarca,
        -- tipo_denuncia,
        -- tipo_de_evento,
        -- tipo_casual,
        -- clasificacion_causal,
        -- causal character varying
        

